github actions: drop the sphinx-action for simple `run` step
Problem: the sphinx-action is returning an inscrutable set of errors,
and ultimately is layering on more complexity than necessary for a
simple `make check`:

```
 Exception occurred:
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
 FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

Solution: switch to just using GitHub Action's `run` step directly